[metadata]
name = primate_uprighting
version = 0.0.1
description-file=README.md
readme = "README.md"
# Homepage = "https://github.com/MatthewMallory/morph_utils"

[project]
readme = "README.md"
# [project.urls]
# Homepage = "https://github.com/MatthewMallory/morph_utils"

[options]
packages = find:
install_requires =
    # scipy
    numpy
    pandas
    argschema
    matplotlib
    neuron_morphology
    morph_utils 
    lims_utils

# [options.entry_points]
# console_scripts =
#     morph_utils_sort_morphology_ids = morph_utils.executable_scripts.sort_morphology_ids:console_script
#     morph_utils_full_morph_soma_correction = morph_utils.executable_scripts.full_morphology_soma_correction:console_script